server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eurekaserver:8070/eureka/"
      
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-agrichain.eu.ngrok.io/realms/master

